---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_fingerprints:
    - 4967c5c8fcb3ce73440ddcdd539ac5b8
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    channel: "eslint-2"
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- dist/
- tests/
- vendor/
