---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

after_script:
  - codeclimate-test-reporter < /coverage/report-lcov/lcov.info

addons:
    code_climate:
        repo_token:
            secure: "e3wmwqbVykJ9hICJE963fX2QAqu7+ujunvkZ7Z/oncZ0Ltwwp+z3VEOqjSD4Y+JRKKWOqGk9GlNBjAQa9dgmaZhfLmXHSzZrQAbuXgPX8wh6+n276dr0U9ArSOj2xuJgm2c2QoS0ckzBE9CEitwI4VZGOMkDUXFa+T18ljRxC3hZSbr/NssYza4aA3k8Dpc1vv9Ee9U8qNql1KJ6nUlmBVnk6djUdLsHzCe50MhxizQSJ1hrToeGDypUnwOs9UPcap13OmUOMQ0teViW76U6n5F3xABNnojSH0LD+kY4X16tXabeQvstegzvVNUhJUu2YNYv9RC7njFszKpCTvrW29oFMvJ70O/H14+f0Irhewf4CS/cETE3o/J6CdyecS6s+KhFgVNag8AmrfpaUuJN+pGTSL5gs0hglLG+Ajfbuv3jTRTWHI35jTA/WLbk0vgwLmXCaNWk4+1Ufa60HlMGVaL+d6svj0i6Q7wJQcBs9YZMZJB6IgqYGxugQv1MqrMrfvG1yBW9xLlb+CBpyi7m1elnJPp3NPU8YQO45UWTN9mxMBLieHCtlHYkZc/w2t+MJCa0q4xpHPWrnZ2suYmx81iJwoRdudBMdx2e+aYbdsW2vhWESyAmWLOFaKwpUWnJ7b513CgVHHCOAZnyk0HBPp0AXBXH8OKPeuaKyfY1+Io="
