---
language: node_js
node_js:
  - "5.10.1"

sudo: true
dist: trusty

env:
  global:
  - GH_REF: github.com/jibeinc/juice.git
  - secure: "FzfsJL+JKN7dhnDHqqv63smGUk0WELry5bwyPn9xS9dnnAdAueZwSly6s/U1HLSYheny3F8i9nqhCHGRNOGugowK8kbO+Gf3P9AoYw/ko9E6Uqh9CSQlGM1mn8likqV1MPpT3a0qAuUBWLojAa3yMH42UmF7jmU1P/NZgnAUKjNPM2D6iHlWwWmZCq/r9R1nvNESVhekewa0YweNEzxLeiwCqijQx+IYU6shY5zKBPgZct/OwVGBfq/qALdL/3G1b48f9hqnqdC2/VAPX29UKFjQSvvci3N0ILQkDRHHQgLD5INAsLiMnRt08AuE9sqgytuyZoI1EcfUOuY4zqYF4/x7407cpiLazPMZElqlHeD2TnjrVpJEvGl6YLzQMSKnrIZKxHFhdJVWusGJ+go7YeZKzo8mCbVGZRDXUr9Md4onyUaaAQElloO8mHTeDEsYLI3tbtW9nc7Yu7+JlbT53wTjOFctNlob0obyo9oLXHxAzrRxIkyQ1qoLsFowiNfTV9aofZYOcOkzmxC0gyKQmYpXFqMPHdEJN/uH0g2MfsGNVj+Enlu7sB5LZz3FjYbNrnHM2Bg/C17g//65LFXhlTdZ3q9DEShbiGwTZgvD5kN0XsSpQIw5HHXhaA/Z8IGmMUWSCLnJPMg8yc8X3CevrWiTxtq+fT97ALfGiT3xUiU="

cache:
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^3"

install:
  - npm install -g bower
  - npm install
  - bower install

before_script:
  - npm run test

script:
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then bash ./deploy.sh; fi

after_script:
  - codeclimate-test-reporter < coverage/report-lcov/lcov.info

addons:
    code_climate:
        repo_token:
            secure: "e3wmwqbVykJ9hICJE963fX2QAqu7+ujunvkZ7Z/oncZ0Ltwwp+z3VEOqjSD4Y+JRKKWOqGk9GlNBjAQa9dgmaZhfLmXHSzZrQAbuXgPX8wh6+n276dr0U9ArSOj2xuJgm2c2QoS0ckzBE9CEitwI4VZGOMkDUXFa+T18ljRxC3hZSbr/NssYza4aA3k8Dpc1vv9Ee9U8qNql1KJ6nUlmBVnk6djUdLsHzCe50MhxizQSJ1hrToeGDypUnwOs9UPcap13OmUOMQ0teViW76U6n5F3xABNnojSH0LD+kY4X16tXabeQvstegzvVNUhJUu2YNYv9RC7njFszKpCTvrW29oFMvJ70O/H14+f0Irhewf4CS/cETE3o/J6CdyecS6s+KhFgVNag8AmrfpaUuJN+pGTSL5gs0hglLG+Ajfbuv3jTRTWHI35jTA/WLbk0vgwLmXCaNWk4+1Ufa60HlMGVaL+d6svj0i6Q7wJQcBs9YZMZJB6IgqYGxugQv1MqrMrfvG1yBW9xLlb+CBpyi7m1elnJPp3NPU8YQO45UWTN9mxMBLieHCtlHYkZc/w2t+MJCa0q4xpHPWrnZ2suYmx81iJwoRdudBMdx2e+aYbdsW2vhWESyAmWLOFaKwpUWnJ7b513CgVHHCOAZnyk0HBPp0AXBXH8OKPeuaKyfY1+Io="
